Repository engelsburg/engelsburg-app, pull requests merged in 2021-09, with the labels that each got.

#19 Changed SolarSystem description WP to API
  lib/constants/api_constants.dart
  lib/models/engelsburg_api/solar_panel.dart
  lib/models/wordpress/page.dart
  lib/pages/solar_panel_page.dart
  lib/services/api_service.dart
Labels: enhancement

#20 Optimizing connection to api and error handling
  lib/constants/api_constants.dart
  lib/constants/app_constants.dart
  lib/models/result.dart
  lib/pages/cateteria_page.dart
  lib/pages/events_page.dart
  lib/pages/news_page.dart
  lib/pages/solar_panel_page.dart
  lib/services/api_service.dart
Labels: feature

#22 add registration page and fix utf 8 problem
  .metadata
  README.md
  analysis_options.yaml
  android/.gitignore
  android/app/build.gradle
  android/build.gradle
  ios/Flutter/AppFrameworkInfo.plist
  l10n.yaml
  lib/constants/app_constants.dart
  lib/main.dart
  lib/models/result.dart
  lib/pages/events_page.dart
  lib/pages/solar_panel_page.dart
  lib/src/app.dart
  lib/src/constants/api_constants.dart
  lib/src/constants/app_constants.dart
  lib/src/constants/asset_path_constants.dart
  lib/src/localization/app_de.arb
  lib/src/localization/app_en.arb
  lib/src/models/engelsburg_api/articles.dart
  lib/src/models/engelsburg_api/cafeteria.dart
  lib/src/models/engelsburg_api/events.dart
  lib/src/models/engelsburg_api/solar_panel.dart
  lib/src/models/result.dart
  lib/src/pages/about_page.dart
  lib/src/pages/about_school_page.dart
  lib/src/pages/cateteria_page.dart
  lib/src/pages/events_page.dart
  lib/src/pages/home_page.dart
  lib/src/pages/news_page.dart
  lib/src/pages/post_detail_page.dart
  lib/src/pages/register_page.dart
  lib/src/pages/settings_page.dart
  lib/src/pages/solar_panel_page.dart
  lib/src/provider/auth.dart
  lib/src/provider/theme.dart
  lib/src/services/api_service.dart
  lib/src/services/shared_prefs.dart
  lib/src/utils/html.dart
  lib/src/utils/random_string.dart
  lib/src/utils/time_ago.dart
  lib/src/widgets/color_grid.dart
  lib/src/widgets/error_box.dart
  pubspec.lock
  pubspec.yaml
  test/unit_test.dart
  test/widget_test.dart
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
  web/index.html
  web/manifest.json
Labels: feature

#32 Reworked result
  lib/src/models/result.dart
  lib/src/pages/cateteria_page.dart
  lib/src/pages/events_page.dart
  lib/src/pages/news_page.dart
  lib/src/pages/solar_panel_page.dart
Labels: documentation, improvements

#30 Login process
  lib/src/constants/api_constants.dart
  lib/src/localization/app_de.arb
  lib/src/localization/app_en.arb
  lib/src/models/engelsburg_api/auth_info_dto.dart
  lib/src/models/engelsburg_api/sign_up_request_dto.dart
  lib/src/models/result.dart
  lib/src/pages/cateteria_page.dart
  lib/src/pages/events_page.dart
  lib/src/pages/home_page.dart
  lib/src/pages/news_page.dart
  lib/src/pages/register_page.dart
  lib/src/pages/solar_panel_page.dart
  lib/src/provider/auth.dart
  lib/src/provider/theme.dart
  lib/src/services/api_service.dart
  pubspec.lock
Labels: bug, feature

#33 Added sqflite db support
  lib/main.dart
  lib/src/localization/app_de.arb
  lib/src/localization/app_en.arb
  lib/src/models/engelsburg_api/articles.dart
  lib/src/pages/article_page.dart
  lib/src/pages/home_page.dart
  lib/src/pages/news_page.dart
  lib/src/services/api_service.dart
  lib/src/services/db_service.dart
  lib/src/utils/time_ago.dart
  pubspec.lock
  pubspec.yaml
Labels: documentation, feature
